// value = {foo} ...
// value = nil ...
// value = 3 ...
// value = true ...
// value = true ...
// value = <native fn> ...
// value = <fn two> ...
// value = Foo ...
// value = Foo instance ...
// value = <fn foo> ...
// 0
fn two() { return 2; }

class Foo {
    fn foo(self) {}
}

print("value = {${"foo"}} ...");
print("value = ${nil} ...");
print("value = ${1 + two()} ...");
print("value = ${true} ...");
print("value = ${!false} ...");
print("value = ${clock} ...");
print("value = ${two} ...");
print("value = ${Foo} ...");
print("value = ${Foo()} ...");
print("value = ${Foo().foo} ...");